In [1]:
import numpy as np


In [54]:
foo = np.array([[2,np.nan,7,15],[4,6,np.nan,12],[3, 55,12,6]])

In [55]:
foo

array([[ 2., nan,  7., 15.],
       [ 4.,  6., nan, 12.],
       [ 3., 55., 12.,  6.]])

In [68]:
col = np.nanmean(foo, axis = 0)

In [69]:
bar = np.where(np.isnan(foo))

In [77]:
foo[bar] = np.take(col, bar[1])
foo

array([[ 2. , 30.5,  7. , 15. ],
       [ 4. ,  6. ,  9.5, 12. ],
       [ 3. , 55. , 12. ,  6. ]])

# task 2 

In [80]:
a = np.array([[1,2,-5,-9],[-2, -5, -1, 5],[1,4,-2,7]])
a

array([[ 1,  2, -5, -9],
       [-2, -5, -1,  5],
       [ 1,  4, -2,  7]])

In [81]:
a < 0

array([[False, False,  True,  True],
       [ True,  True,  True, False],
       [False, False,  True, False]])

In [82]:
a[a<0] = 0

In [83]:
a

array([[1, 2, 0, 0],
       [0, 0, 0, 5],
       [1, 4, 0, 7]])