Return the indices of elements where the given condition is satisfied



In [57]:
import numpy as np

In [58]:
foo = np.arange(start=1, stop=9)

In [59]:
print(foo)

[1 2 3 4 5 6 7 8]


In [60]:
for i in foo:
    if i % 2:
        print(list(foo).index(i))
    

0
2
4
6


Find indices of elements equal to zero in a NumPy array

In [66]:

bar = np.random.randint(19, size=10)
print(bar)

[12 12 15  0  6 13  3  2  9 17]


In [67]:
for i in bar:
    if i == 0:
        print(list(bar).index(i))
        


3


How to get values of NumPy array at certain index position


In [70]:
bim = np.random.randint(19, size=10)
print(bim)

[ 9 10  7  5 13  0 12  7  4 14]


In [72]:
x = int(input('please enter the number of integer from array'))
print(bim[x-1])

please enter the number of integer from array5
13
