# 1. Check elements present in the Numpy array


In [6]:
import numpy as np

# Example 1

In [16]:
n_array1  = np.array([[2,  6,  11],
                     [16,  21,  26],
                     [31, 36, 41]])

In [17]:
print('Array:', n_array1)

Array: [[ 2  6 11]
 [16 21 26]
 [31 36 41]]


In [22]:
print(n_array1 == (2, 36, 11))

[[ True False  True]
 [False False False]
 [False  True False]]


# Example 2

In [25]:
n_array2 =  np.array([[0,  17,  36],
                     [215,  38,  73],
                     [22, 52, 64]])
n_array3 =  np.array([[2,  6,  11],
                     [16,  0,  21],
                     [12, 23, 17]])

In [26]:
check_elements = np.in1d(n_array2, n_array3)
check_elements

array([ True,  True, False, False, False, False, False, False, False])

# Example 3

In [33]:
n_array = np.array([[2,  6,  11],
                     [16,  21,  26],
                     [31, 36, 41]])
n_array
print(6 in n_array, 15 in n_array, 41 in n_array )

True False True


# 2. How to get values of an array at certain index positions?

# Example 1

In [81]:
array1  = np.array([[7,  23,  1],
                    [91,  3, 67]])
print('First array:')
print(array1)  
array2  = np.array([0,  0,  0])
print("Second array:")
print(array2)

array1.put([0,  3, 5], array2) #take list of 0 from array2 and put them in 1st, 4th and 6th positions of array1
print('Result:')
print(array1)


First array:
[[ 7 23  1]
 [91  3 67]]
Second array:
[0 0 0]
Result:
[[ 0 23  1]
 [ 0  3  0]]


# Example 2

In [125]:
n_array4 = np.array([0, 17, 36, 215, 28, 73, 22])
ind_pos = np.array([1,3,5])

print(n_array4[ind_pos])

[ 17 215  73]


# Example 3

In [127]:
n_array5  = np.array([[2,  6,  11], 
                     [16,  21,  26],
                     [31, 36, 41]])
n_array5[[0], [0]]

array([2])