# How to access different rows of a multidimensional NumPy array?


In [1]:
import numpy 
mass = numpy.array([[128,2,134,8],[2,44,3,4],[2,1,5,6]]) 
print(mass)

[[128   2 134   8]
 [  2  44   3   4]
 [  2   1   5   6]]


In [2]:
mass

array([[128,   2, 134,   8],
       [  2,  44,   3,   4],
       [  2,   1,   5,   6]])

In [5]:
mass_res = mass[[0,1]]
print(mass_res)

[[128   2 134   8]
 [  2  44   3   4]]


# Get row numbers of NumPy array having element larger than X

In [7]:
import numpy 
mass = numpy.array([[128,2,134,8],[2,44,3,4],[2,1,5,6]]) 
print(mass)

[[128   2 134   8]
 [  2  44   3   4]
 [  2   1   5   6]]


In [8]:
E = 10
out = numpy.where(numpy.any(mass > E, axis = 1 ))
print(out)

(array([0, 1], dtype=int32),)


# Get filled the diagonals of NumPy array

In [9]:
import numpy 
mass = numpy.array([[128,2,134],[2,44,3],[2,1,5]]) 
print(mass)

[[128   2 134]
 [  2  44   3]
 [  2   1   5]]


In [10]:
numpy.fill_diagonal(mass, 0)
print(mass)

[[  0   2 134]
 [  2   0   3]
 [  2   1   0]]
